### ISSUE TITLE
error whem moving message for new api (rc 1.1.X) for INBOX folder

### ISSUE THREAD

**Issue by mckaygerhard** [JohnDoh/Roundcube-Plugin-Context-Menu#65]
when enabled the contexmenu in rc 1.1.X newer vrsion and use the move command theres a error (that i cannot debug to find why) ..

1) select a message in INBOX
2) right click and go to move.. menu 
3) select to move to any other folder
4) message its moved sussessfully BUT ERROR POPUP appears

this only happends when message are in inbox and with rc 1.1.0
i cannot see any error on the logs and i enabled all debug level and logs of commands

php does not show any..

NOTE: i open the bug here, but i think the problem its at rc API level, and not from plugin .. due only happends in rc 1.1.0, another reason could be changes in the rc 1.1.0 api

**Comment by mckaygerhard** [comment]
another tip: well if move by drag n drop the message, errors not show..

**Comment by JohnDoh** [comment]
works for me. what version of the contextmenu plugin are you running? For rc 1.1 it should be version 2.1. the version number should be written in the composer.json file.

**Comment by mckaygerhard** [comment]
i runnig the lasted, 2.1, with rc 1.1.0, php 5.3.8 and extensible enought hardware resources..

specially, the problem ocurs only when there no message selected and just right click.. if there already a message selected and previewed, then it works

another tips, if u have selected in preferences that on each action of read or deletion, continue to nest message errors does not happened.

**Comment by JohnDoh** [comment]
did you have a previous version installed? if so please could you confirm that the contextmemu.js file was updated properly (and the .min file, if you have it) and that an old version is not being cached by your browser or anything like that?

What broswer are you using? Are there any JS errors?

**Comment by mckaygerhard** [comment]
was always fresh install, using firefox 3.6.24, also chromium 28 and iceweasel 10 and 30, opera lasted too

note that if u siad me that "too older blah blah" i do not use the gpl software for put a maqil server at my home, that its nonsense due there are a lot of free webmail providrs..
i used opensource or gpl software for company, so in enterprise environments we do not use the lasted apps, we used stable and well knowed apps, and enterprise apps such like oracle supports only firefox 8 and 17 LTS releases

**Comment by JohnDoh** [comment]
I have iceweasel 31 not 30 and it works fine in that. I have also tried with Opera 27 and it works fine in that.

The reason I asked about the caching was that I think that with all the changes for multi folder search support I did have to change how the move function worked but it was a long time ago and I cannot remember the exact details so I just wondered if you were running an old version.

Just to make sure I haven't missunder stood. I login, inbox comes up full of messages then:
1) Right click on any message
2) "More"
3) "Move to..."
4) Select any folder apart from the current one.

And there are no JS errors in your browser right?
Do you see the "Moving message(s)..." spinner?

You said an error message appears, what is the error?

Do you have any other plugins running? If so please try with them disabled.

**Comment by mckaygerhard** [comment]
ok lest doit that:

a) do not enable any other plugin
b) enable debugging
c) cach any interface notificacion (moving message) or browser error console

So then this are the detailed:
Server: now soft are: rc 1.1.0, lighttpd 1.4.35, php 5.3.10, postgresql 9.1
Client: 1) firefox 30, 2) opera 26, 3) iceweasel 11, 4) iceweasel 27, 5) chromium 27

in main there are 3 message not readed!
right click the firts (without reading)
"More"->"Move to..."->"SPAM"

now there the results:
in 1) no problem, but contextmenu do not disapears, i must click outside of the menu
in 2) same as in 1), i must click outside to dissapear
in 3) move but show an error, here the browsercompatibility are disabled 
in 4) move but show an error, here the browsercompatibility are enabled and its mandatory
in 5) move but show an error, here the browsercompatibility are enabled and its mandatory
no errors in the browser console in any case, no log error in any log of rc

so i deduce that u'r new release may have some conflicts with the browsercompatibility plugin and this are a oficial plugin released with roundcube.. 

so this bug must be resolved, due some of these brosers are enabled at the mobile devices, i explain this:

i make some test in some mobiles, and the errors happening.. the compatibility plugin are necesary due not all enterprise environment have or may be permit to let pass or permit to normal users to update their browsers.. theire all are blocked users and remenber in this enviroment ther lot of employers

**Comment by mckaygerhard** [comment]
i confirmed only in lasted version of browsers error do not show.. and if i moved the message with drag and drop there no errors..., for all of the rest of browsers contexmenu do not dissaper after the action.. event if i do a right click outside of..

**Comment by mckaygerhard** [comment]
hello @JohnDoh this issue are only related to "moving" action from contextmenu.. ther still other two problems that i separate from here (issue), "do not hide when done" (solved with commit  db0dca4 ) and "do not hide if outsideclick/action not performed" when action are not completed and users change the dessire and goes to another button or link, menu still are in screen

**Comment by JohnDoh** [comment]
What is the error that comes up?

I closed the other ticket because I cannot recreate any problem with the menu closing when the user clicks away. I suspect that what ever is causing the error when you move a message is also breaking the hiding code.

I have very little access to old browser but I was able to find an old PC and for me the contextmenu works fine in both FF3.6 and IE8 - both require the legacy_browser plugin, is that what you mean by "browsercompatibility plugin"? So I don't think there is any major problem between this plugin and the legacy_browser plugin shipped with Roundcube.

You mentioned something about testing in mobiles? Roundcube does not current have a mobile interface. The current skins (classic and larry) are not intended for use on mobiles. This plugin is not designed for use on mobiles.

You said that in current browsers it works fine so perhaps it is just an old browser support issue. I see here that jQuery 2.x (used in Roundcube) does not support old browsers http://jquery.com/browser-support/ so may be some of the events needed for this plugin do not work in there. There is nothing I can do about that.

**Comment by mckaygerhard** [comment]
yes and not, ...

yes, **with lasted commit now when action are performed menu oes out..** good!.

no due **if action are not performed (user right click but changes of mind) and doit a click outside of menu, menu does not out.. stay here**, event in newer browser..

about the jquery, roudncube has a compatibility mode, so older browsers and jquery are not the issue.. works well event in ff 4.X

about mobiles, rc runs on mobiles, using the responsible skins, rouncube works great,

**Comment by JohnDoh** [comment]
......

Still not posted the error message!

> about mobiles, rc runs on mobiles, using the responsible skins, rouncube works great, 

There is no responsive skin for Roundcube.

> yes, with lasted commit now when action are performed menu oes out.. good!.

the latest commit? 7f47e85b5000d971b6cbda18d60464d44eaccc93? really, nothing changed there only a bit of code cleanup. Again makes no sense.

**Comment by mckaygerhard** [comment]
sorry a mean lasted in that moment,the commit was db0dca4 , but still if u right click menu show, but if no choose any action menu performs still remain until page reload

responsive skin are not free... u must pay..

about the eerror in this issue , are when choose firts message not read yet and choose to move to another..

**Comment by JohnDoh** [comment]
Please test using the Larry or Classic skin distributed with Roundcube.

And if there is still an error please tell me what it is. Not just what causes it. What the actual message is that comes up.

**Comment by mckaygerhard** [comment]
still using lastes browser, clasic skin, .. the skin are not related , the last commit probe it

**Comment by JohnDoh** [comment]
I'm going to close this ticket now, its been over a month neither I or apparently any one else can recreate the issues you are talking about. I do not believe there is any problem with the plugin.

**Comment by mckaygerhard** [comment]
nobody reports that due nobody takes care of.. i take care due i manage a amount of users and tha users are not expert in computers
